<?php

namespace Jstewmc\Rtf\Element\Control\Word;

/**
 * The "\cxa" control word
 *
 * The "\cxa" control word indicates text automatically generated by the CAT system,
 * like the "Q." in Questions. Keep in mind, this does not include the automatically
 * translated punctuation at the end of sentences, only text which cannot be edited
 * by the user.
 *
 * For example:
 *
 *     \par\s1{\cxa Q. }{\*\cxs STAEUT}State {\*\cxs UR}your...
 *
 * @author     Jack Clayton
 * @copyright  2015 Jack Clayton
 */
class Cxa extends Word
{
	// nothing yet	
}
